/**
 * Crisis Director — generates emergent crises per timeline based on colony state.
 *
 * Replaces static SCENARIOS for turns 2-11. Turn 1 (Landfall) and the final turn
 * (Legacy Assessment) remain fixed milestones for narrative anchoring.
 */

import type { Department, HexacoProfile, TurnOutcome } from '../engine/core/state.js';
import type { CrisisOption } from './contracts.js';
import type { LlmProvider } from '../engine/types.js';
import { SCENARIOS } from './research/scenarios.js';

/** Event category. Scenario-defined, not a fixed union. */
export type EventCategory = string;
/** @deprecated Use EventCategory */
export type CrisisCategory = EventCategory;

/** A turn event generated by the Event Director. */
export interface DirectorEvent {
  title: string;
  /** Event description presented to the commander */
  description: string;
  options: CrisisOption[];
  riskyOptionId: string;
  riskSuccessProbability: number;
  category: string;
  researchKeywords: string[];
  relevantDepartments: Department[];
  turnSummary: string;
}

/** @deprecated Use DirectorEvent */
export type DirectorCrisis = DirectorEvent & { crisis?: string };

/** Context passed to the Event Director for generating turn events. */
export interface DirectorContext {
  turn: number;
  year: number;
  leaderName: string;
  leaderArchetype: string;
  leaderHexaco: HexacoProfile;
  /** Scenario state metrics (population, morale, resources, etc.) */
  state: Record<string, number>;
  /** Political/social state variables */
  politics: Record<string, number | string | boolean>;
  aliveCount: number;
  /** Count of agents born at the settlement (vs arrived from elsewhere) */
  nativeBornCount: number;
  recentDeaths: number;
  recentBirths: number;
  previousEvents: Array<{
    turn: number;
    title: string;
    category: string;
    selectedOptionId?: string;
    decision?: string;
    outcome: TurnOutcome;
  }>;
  toolsForged: string[];
  driftSummary: Array<{ name: string; role: string; openness: number; conscientiousness: number }>;
  /** Key outputs from forged tools last turn */
  recentToolOutputs: Array<{ name: string; department: string; output: string }>;
  /** Agent mood summary from last turn */
  agentMoodSummary?: string;

  // Legacy aliases (backward compat with existing scenario hooks)
  /** @deprecated Use state */
  colony?: Record<string, number>;
  /** @deprecated Use previousEvents */
  previousCrises?: DirectorContext['previousEvents'];
  /** @deprecated Use nativeBornCount */
  marsBornCount?: number;
}

const DEFAULT_DIRECTOR_INSTRUCTIONS = `You are the Event Director for a simulation. You observe simulation state and generate events that test the settlement's weaknesses, exploit consequences of prior decisions, and create narrative tension.

RULES:
1. Each event has exactly 2-3 options with stable IDs (option_a, option_b, option_c)
2. Exactly one option must be marked isRisky: true (higher upside, higher downside)
3. Events must reference domain-appropriate knowledge
4. Never repeat an event category from the immediately previous turn
5. Escalate: later events should reference consequences of earlier decisions
6. Calibrate difficulty to current state: struggling settlements get survivable events, thriving ones get existential ones
7. Include actual state numbers in the event description
8. Specify which departments should analyze (2-4 departments per event)

Return ONLY valid JSON:
{"title":"Event Title","description":"Full description with specific state numbers...","options":[{"id":"option_a","label":"Option Label","description":"What this option does","isRisky":false},{"id":"option_b","label":"Risky Option","description":"Higher upside, higher risk","isRisky":true}],"riskyOptionId":"option_b","riskSuccessProbability":0.55,"category":"environmental","researchKeywords":["keyword"],"relevantDepartments":["dept_id"],"turnSummary":"One sentence: why this event emerged from prior decisions"}`;

/** Build the prompt for the director given simulation context. */
function buildDirectorPrompt(ctx: DirectorContext): string {
  const events = ctx.previousEvents ?? ctx.previousCrises ?? [];
  const prevHistory = events.length
    ? events.map(e => `  Turn ${e.turn}: "${e.title}" (${e.category}) -> ${e.outcome}${e.decision ? ': ' + e.decision.slice(0, 80) : ''}`).join('\n')
    : '  None yet (this is the first emergent turn)';

  const prevCategories = events.map(e => e.category);
  const lastCategory = prevCategories[prevCategories.length - 1] || 'none';

  // Build state summary from generic key-value pairs
  const stateLines = Object.entries(ctx.state).map(([k, v]) => {
    const display = typeof v === 'number' && v < 1 && v > 0 ? `${Math.round(v * 100)}%` : String(v);
    return `- ${k}: ${display}`;
  }).join('\n');

  const politicsLines = Object.entries(ctx.politics).map(([k, v]) => {
    const display = typeof v === 'number' && v < 1 && v > 0 ? `${Math.round(v * 100)}%` : String(v);
    return `- ${k}: ${display}`;
  }).join('\n');

  return `GENERATE EVENT FOR TURN ${ctx.turn}, YEAR ${ctx.year}

SIMULATION STATE:
- Commander: ${ctx.leaderName} (${ctx.leaderArchetype})
- Population: ${ctx.aliveCount} alive (${ctx.nativeBornCount} native-born)
- Recent: +${ctx.recentBirths} births, -${ctx.recentDeaths} deaths
${stateLines}
${politicsLines ? `\nPOLITICS/SOCIAL:\n${politicsLines}` : ''}
- Tools forged so far: ${ctx.toolsForged.length}

COMMANDER PERSONALITY (HEXACO):
O: ${ctx.leaderHexaco.openness.toFixed(2)} C: ${ctx.leaderHexaco.conscientiousness.toFixed(2)} E: ${ctx.leaderHexaco.extraversion.toFixed(2)}
A: ${ctx.leaderHexaco.agreeableness.toFixed(2)} Em: ${ctx.leaderHexaco.emotionality.toFixed(2)} HH: ${ctx.leaderHexaco.honestyHumility.toFixed(2)}

DECISION HISTORY:
${prevHistory}
${ctx.recentToolOutputs.length ? `\nTOOL INTELLIGENCE (what department agents computed last turn):\n${ctx.recentToolOutputs.slice(0, 4).map(t => `  [${t.department}] ${t.name}: ${t.output.slice(0, 120)}`).join('\n')}\nUse these findings to generate an event that follows from what the tools revealed.` : ''}
${ctx.agentMoodSummary ? `\nAGENT MOOD: ${ctx.agentMoodSummary}` : ''}

CONSTRAINT: Do NOT use category "${lastCategory}" (used last turn). Pick a different category.

Generate an event that tests this settlement based on its current state, past decisions, and tool intelligence. The event should feel like a consequence of what happened before. Return JSON only.`;
}

/** Parse director LLM response into DirectorCrisis. */
function parseDirectorResponse(text: string): DirectorCrisis | null {
  // Try to extract JSON
  let depth = 0, start = -1;
  for (let i = 0; i < text.length; i++) {
    if (text[i] === '{') { if (depth === 0) start = i; depth++; }
    if (text[i] === '}') { depth--; if (depth === 0 && start >= 0) {
      try {
        const raw = JSON.parse(text.slice(start, i + 1));
        if (raw.title && (raw.description || raw.crisis) && raw.options) {
          return {
            title: raw.title,
            description: raw.description || raw.crisis,
            crisis: raw.crisis || raw.description,
            options: (raw.options || []).map((o: any, idx: number) => ({
              id: o.id || `option_${String.fromCharCode(97 + idx)}`,
              label: o.label || `Option ${String.fromCharCode(65 + idx)}`,
              description: o.description || '',
              isRisky: o.isRisky === true,
            })),
            riskyOptionId: raw.riskyOptionId || raw.options?.find((o: any) => o.isRisky)?.id || 'option_b',
            riskSuccessProbability: typeof raw.riskSuccessProbability === 'number' ? raw.riskSuccessProbability : 0.5,
            category: raw.category || 'infrastructure',
            researchKeywords: raw.researchKeywords || [],
            relevantDepartments: raw.relevantDepartments || ['medical', 'engineering'],
            turnSummary: raw.turnSummary || '',
          };
        }
      } catch { /* try next block */ }
      start = -1;
    }}
  }
  return null;
}

/** Fallback events if director fails. */
const FALLBACK_EVENTS: DirectorEvent[] = [
  {
    title: 'System Malfunction',
    description: 'A critical support component has developed an intermittent failure. Operating at 60% efficiency. Reserves are becoming dangerously low.',
    options: [
      { id: 'option_a', label: 'Emergency repair', description: 'Divert all engineering to immediate repair. Safe but halts all other construction for 2 weeks.', isRisky: false },
      { id: 'option_b', label: 'Improvised bypass', description: 'Build a bypass from non-standard parts. Faster but untested. Could fail catastrophically.', isRisky: true },
    ],
    riskyOptionId: 'option_b', riskSuccessProbability: 0.5, category: 'infrastructure',
    researchKeywords: ['life support failure', 'ECLSS redundancy'], relevantDepartments: ['engineering', 'medical'],
    turnSummary: 'Infrastructure strain triggered a life support component failure.',
  },
  {
    title: 'Supply Shortage',
    description: 'Unexpected contamination of reserves has rendered 30% of stored supplies unusable. The settlement must decide how to manage the shortfall.',
    options: [
      { id: 'option_a', label: 'Strict rationing', description: 'Reduce caloric intake by 25% colony-wide for 3 months. Morale will drop.', isRisky: false },
      { id: 'option_b', label: 'Emergency crop acceleration', description: 'Boost grow lights to 24/7, triple nutrient concentration. Could yield 2x harvest or kill the crops.', isRisky: true },
    ],
    riskyOptionId: 'option_b', riskSuccessProbability: 0.55, category: 'resource',
    researchKeywords: ['food security mars', 'hydroponic acceleration'], relevantDepartments: ['agriculture', 'medical'],
    turnSummary: 'Food contamination created an unexpected supply crisis.',
  },
  {
    title: 'Social Unrest',
    description: 'Tensions between work crews have escalated into a refusal to cooperate. Two factions have formed around competing visions. Productivity has dropped 40%.',
    options: [
      { id: 'option_a', label: 'Mediation program', description: 'Mandatory conflict resolution sessions. Slow but addresses root causes.', isRisky: false },
      { id: 'option_b', label: 'Restructure work crews', description: 'Break up existing teams and reassign. Disrupts established relationships.', isRisky: true },
    ],
    riskyOptionId: 'option_b', riskSuccessProbability: 0.45, category: 'psychological',
    researchKeywords: ['group conflict isolation', 'crew cohesion'], relevantDepartments: ['psychology', 'governance'],
    turnSummary: 'Accumulated social pressure erupted into factional conflict.',
  },
];

export class EventDirector {
  /**
   * Generate a turn event. Uses AgentOS generateText().
   */
  async generateEvent(ctx: DirectorContext, provider: LlmProvider = 'openai', model: string = 'gpt-5.4', instructions?: string): Promise<DirectorEvent> {
    const prompt = buildDirectorPrompt(ctx);
    const systemInstructions = instructions || DEFAULT_DIRECTOR_INSTRUCTIONS;

    try {
      const { generateText } = await import('@framers/agentos');
      const result = await generateText({
        provider,
        model,
        prompt: systemInstructions + '\n\n' + prompt,
      });

      const event = parseDirectorResponse(result.text);
      if (event) {
        console.log(`  [director] Generated: "${event.title}" (${event.category}) for ${ctx.leaderName}`);
        return event;
      }
      console.log(`  [director] Failed to parse response for ${ctx.leaderName}, using fallback`);
    } catch (err) {
      console.log(`  [director] Error for ${ctx.leaderName}: ${err}`);
    }

    // Fallback
    const fallback = FALLBACK_EVENTS[ctx.turn % FALLBACK_EVENTS.length];
    console.log(`  [director] Using fallback: "${fallback.title}"`);
    return { ...fallback };
  }

  /** @deprecated Use generateEvent */
  async generateCrisis(ctx: DirectorContext, provider: LlmProvider = 'openai', model: string = 'gpt-5.4', instructions?: string): Promise<DirectorEvent> {
    return this.generateEvent(ctx, provider, model, instructions);
  }

  /**
   * Get a milestone crisis (Turn 1 or final turn).
   * These are fixed for narrative anchoring.
   */
  getMilestoneCrisis(turn: number, maxTurns: number): DirectorCrisis | null {
    if (turn === 1) {
      const s = SCENARIOS[0];
      return {
        title: s.title,
        description: s.crisis,
        crisis: s.crisis,
        options: s.options || [
          { id: 'option_a', label: 'Arcadia Planitia', description: 'Flat basalt plains, safe, ice access', isRisky: false },
          { id: 'option_b', label: 'Valles Marineris rim', description: 'Canyon rim, mineral rich, hazardous terrain', isRisky: true },
        ],
        riskyOptionId: 'option_b',
        riskSuccessProbability: s.riskSuccessProbability,
        category: 'infrastructure',
        researchKeywords: s.researchKeywords,
        relevantDepartments: ['medical', 'engineering'],
        turnSummary: 'Colony ship in orbit. Safe plains or mineral-rich canyon rim: the first decision shapes everything.',
      };
    }

    if (turn === maxTurns) {
      const s = SCENARIOS[11]; // Legacy Assessment
      const crisisText = s?.crisis || 'Earth requests a comprehensive status report on your colony. Assess your legacy.';
      return {
        title: s?.title || 'Legacy Assessment',
        description: crisisText,
        crisis: crisisText,
        options: [
          { id: 'option_a', label: 'Honest assessment', description: 'Report factually, including failures and regrets', isRisky: false },
          { id: 'option_b', label: 'Ambitious projection', description: 'Emphasize achievements, propose bold next-century vision', isRisky: true },
        ],
        riskyOptionId: 'option_b',
        riskSuccessProbability: 0.5,
        category: 'political',
        researchKeywords: ['Mars colony long-term projections'],
        relevantDepartments: ['governance', 'psychology', 'medical', 'engineering'],
        turnSummary: 'Earth demands a full status report. The commander must decide: honest accounting of failures, or bold vision for the next century.',
      };
    }

    return null; // Not a milestone turn
  }
}

/** @deprecated Use EventDirector */
export const CrisisDirector = EventDirector;
