/**
 * Event Director — generates emergent events per timeline based on world state.
 *
 * Each turn, the director observes resource levels, population health, prior
 * decisions, tool intelligence, and mood data. It produces events that test
 * weaknesses, exploit consequences of prior choices, and escalate over time.
 * Events can be crises, opportunities, disruptions, or transitions depending
 * on the scenario's eventNoun label.
 *
 * Milestone events (turn 1 and final turn) are fixed by the scenario for
 * narrative anchoring. All other turns use emergent generation.
 */

import type { Department, HexacoProfile, TurnOutcome } from '../engine/core/state.js';
import type { CrisisOption } from './contracts.js';
import type { LlmProvider } from '../engine/types.js';
import { SCENARIOS } from './research/scenarios.js';

/** Event category. Scenario-defined, not a fixed union. */
export type EventCategory = string;
/** @deprecated Use EventCategory */
export type CrisisCategory = EventCategory;

/** A turn event generated by the Event Director. */
export interface DirectorEvent {
  title: string;
  /** Event description presented to the commander */
  description: string;
  options: CrisisOption[];
  riskyOptionId: string;
  riskSuccessProbability: number;
  category: string;
  researchKeywords: string[];
  relevantDepartments: Department[];
  turnSummary: string;
}

/** Batch of events generated for a single turn. */
export interface DirectorEventBatch {
  events: DirectorEvent[];
  pacing: 'calm' | 'normal' | 'intense';
  reasoning: string;
}

/** @deprecated Use DirectorEvent */
export type DirectorCrisis = DirectorEvent & { crisis?: string };

/** Context passed to the Event Director for generating turn events. */
export interface DirectorContext {
  turn: number;
  year: number;
  leaderName: string;
  leaderArchetype: string;
  leaderHexaco: HexacoProfile;
  /** Scenario state metrics (population, morale, resources, etc.) */
  state: Record<string, number>;
  /** Political/social state variables */
  politics: Record<string, number | string | boolean>;
  aliveCount: number;
  /** Count of agents born at the settlement (vs arrived from elsewhere) */
  nativeBornCount: number;
  recentDeaths: number;
  recentBirths: number;
  previousEvents: Array<{
    turn: number;
    title: string;
    category: string;
    selectedOptionId?: string;
    decision?: string;
    outcome: TurnOutcome;
  }>;
  toolsForged: string[];
  driftSummary: Array<{ name: string; role: string; openness: number; conscientiousness: number }>;
  /** Key outputs from forged tools last turn */
  recentToolOutputs: Array<{ name: string; department: string; output: string }>;
  /** Agent mood summary from last turn */
  agentMoodSummary?: string;
  /** Knowledge topic IDs available in the scenario knowledge bundle.
   *  Provides grounding for researchKeywords so events tie back to real citations. */
  knowledgeTopics?: string[];
  /** Categories the scenario knows about (from KnowledgeBundle.categoryMapping). */
  knowledgeCategories?: string[];

  // Legacy aliases (backward compat with existing scenario hooks)
  /** @deprecated Use state */
  colony?: Record<string, number>;
  /** @deprecated Use previousEvents */
  previousCrises?: DirectorContext['previousEvents'];
  /** @deprecated Use nativeBornCount */
  marsBornCount?: number;
}

const DEFAULT_DIRECTOR_INSTRUCTIONS = `You are the Event Director for a simulation. You observe simulation state and generate events that test the settlement's weaknesses, exploit consequences of prior decisions, and create narrative tension.

You generate 1 to {MAX_EVENTS} events per turn. Decide how many based on:
- World stability: low morale + low resources + recent failures = more events
- Narrative pacing: vary the rhythm, don't always generate the maximum
- Prior turn intensity: if the last turn had many events, consider fewer this turn
- Turn position: early turns can have fewer events for ramp-up

RULES:
1. Each event has exactly 2-3 options with stable IDs (option_a, option_b, option_c)
2. Exactly one option per event must be marked isRisky: true
3. Events must reference domain-appropriate knowledge
4. No two events in the same batch should share a category
5. Never repeat a category from the immediately previous turn
6. Escalate: later events should reference consequences of earlier decisions
7. Include actual state numbers in event descriptions
8. Specify which departments should analyze each event (2-4 per event)

OPTION POLARIZATION (CRITICAL — drives leader divergence):
The whole point of the simulation is to surface how different personalities
produce different civilizations from identical starting conditions. Boring
options that mostly come out the same defeat that purpose. Make the safe
option and the risky option DRAMATICALLY DIFFERENT in:
  - Magnitude of effect (safe = small/incremental; risky = transformative or catastrophic)
  - Scope of change (safe = preserve status quo; risky = restructure something fundamental)
  - Time horizon (safe = address immediate symptom; risky = bet on a long arc)
  - Required commitment (safe = reversible; risky = burns bridges)

If the description of option_a could plausibly be swapped with option_b
without changing much, the options are too similar — rewrite them so
they reflect genuinely opposed philosophies (cautious-protocol vs
bold-experiment, conservation vs expansion, equity vs efficiency, etc.).

The risky option should be neither obviously stupid nor obviously correct.
Aim for ~40-65% success probability so high-openness leaders genuinely
gamble while high-conscientiousness leaders genuinely have a defensible
case for the safe path.

Return ONLY valid JSON:
{"events":[{"title":"...","description":"...","options":[{"id":"option_a","label":"...","description":"...","isRisky":false},{"id":"option_b","label":"...","description":"...","isRisky":true}],"riskyOptionId":"option_b","riskSuccessProbability":0.55,"category":"environmental","researchKeywords":["keyword"],"relevantDepartments":["dept_id"],"turnSummary":"One sentence"}],"pacing":"normal","reasoning":"Why this many events"}`;

/** Build the prompt for the director given simulation context. */
function buildDirectorPrompt(ctx: DirectorContext, maxEvents: number = 3): string {
  const events = ctx.previousEvents ?? ctx.previousCrises ?? [];
  const prevHistory = events.length
    ? events.map(e => `  Turn ${e.turn}: "${e.title}" (${e.category}) -> ${e.outcome}${e.decision ? ': ' + e.decision.slice(0, 80) : ''}`).join('\n')
    : '  None yet (this is the first emergent turn)';

  const prevCategories = events.map(e => e.category);
  const lastCategory = prevCategories[prevCategories.length - 1] || 'none';

  // Build state summary from generic key-value pairs
  const stateLines = Object.entries(ctx.state).map(([k, v]) => {
    const display = typeof v === 'number' && v < 1 && v > 0 ? `${Math.round(v * 100)}%` : String(v);
    return `- ${k}: ${display}`;
  }).join('\n');

  const politicsLines = Object.entries(ctx.politics).map(([k, v]) => {
    const display = typeof v === 'number' && v < 1 && v > 0 ? `${Math.round(v * 100)}%` : String(v);
    return `- ${k}: ${display}`;
  }).join('\n');

  // Knowledge grounding: tell the director what topics/categories the scenario
  // has citations for, so its researchKeywords match real entries in the bundle.
  // This drives downstream citation retrieval (recallResearch + getResearchFromBundle).
  const knowledgeBlock: string[] = [];
  if (ctx.knowledgeTopics?.length) {
    knowledgeBlock.push(
      '',
      'KNOWLEDGE BUNDLE TOPICS (use these in researchKeywords for accurate citation retrieval):',
      ctx.knowledgeTopics.slice(0, 12).map(t => `  - ${t}`).join('\n'),
    );
  }
  if (ctx.knowledgeCategories?.length) {
    knowledgeBlock.push(
      '',
      'KNOWLEDGE BUNDLE CATEGORIES (prefer one of these for the event category field):',
      `  ${ctx.knowledgeCategories.slice(0, 12).join(', ')}`,
    );
  }

  return `GENERATE EVENT FOR TURN ${ctx.turn}, YEAR ${ctx.year}

SIMULATION STATE:
- Commander: ${ctx.leaderName} (${ctx.leaderArchetype})
- Population: ${ctx.aliveCount} alive (${ctx.nativeBornCount} native-born)
- Recent: +${ctx.recentBirths} births, -${ctx.recentDeaths} deaths
${stateLines}
${politicsLines ? `\nPOLITICS/SOCIAL:\n${politicsLines}` : ''}
- Tools forged so far: ${ctx.toolsForged.length}

COMMANDER PERSONALITY (HEXACO):
O: ${ctx.leaderHexaco.openness.toFixed(2)} C: ${ctx.leaderHexaco.conscientiousness.toFixed(2)} E: ${ctx.leaderHexaco.extraversion.toFixed(2)}
A: ${ctx.leaderHexaco.agreeableness.toFixed(2)} Em: ${ctx.leaderHexaco.emotionality.toFixed(2)} HH: ${ctx.leaderHexaco.honestyHumility.toFixed(2)}

Use this profile to colour (not determine) the next event. A high-openness commander should face events that reward novel responses and punish rigid thinking. A high-conscientiousness commander should face events that reward procedure and expose improvisation gaps. A high-emotionality commander should face events that test how their human-impact weighting plays against the math. Events are not rigged against the commander; they reflect the colony they shaped. Two commanders with opposing profiles should diverge into genuinely different pressures by turn 3.

DECISION HISTORY:
${prevHistory}
${ctx.recentToolOutputs.length ? `\nTOOL INTELLIGENCE (what department agents computed last turn):\n${ctx.recentToolOutputs.slice(0, 4).map(t => `  [${t.department}] ${t.name}: ${t.output.slice(0, 120)}`).join('\n')}\nUse these findings to generate an event that follows from what the tools revealed.` : ''}
${ctx.agentMoodSummary ? `\nAGENT MOOD: ${ctx.agentMoodSummary}` : ''}
${knowledgeBlock.join('\n')}

CONSTRAINT: Do NOT use category "${lastCategory}" (used last turn). Pick a different category.

Generate 1 to ${maxEvents} events for this turn. Each event should feel like a consequence of what happened before. If the world is stable, 1 event is fine. If pressure is mounting, generate more. Return JSON with an "events" array.`;
}

/** Parse director LLM response into DirectorCrisis. */
function parseDirectorResponse(text: string): DirectorCrisis | null {
  // Try to extract JSON
  let depth = 0, start = -1;
  for (let i = 0; i < text.length; i++) {
    if (text[i] === '{') { if (depth === 0) start = i; depth++; }
    if (text[i] === '}') { depth--; if (depth === 0 && start >= 0) {
      try {
        const raw = JSON.parse(text.slice(start, i + 1));
        if (raw.title && (raw.description || raw.crisis) && raw.options) {
          return {
            title: raw.title,
            description: raw.description || raw.crisis,
            crisis: raw.crisis || raw.description,
            options: (raw.options || []).map((o: any, idx: number) => ({
              id: o.id || `option_${String.fromCharCode(97 + idx)}`,
              label: o.label || `Option ${String.fromCharCode(65 + idx)}`,
              description: o.description || '',
              isRisky: o.isRisky === true,
            })),
            riskyOptionId: raw.riskyOptionId || raw.options?.find((o: any) => o.isRisky)?.id || 'option_b',
            riskSuccessProbability: typeof raw.riskSuccessProbability === 'number' ? raw.riskSuccessProbability : 0.5,
            category: raw.category || 'infrastructure',
            researchKeywords: raw.researchKeywords || [],
            relevantDepartments: raw.relevantDepartments || ['medical', 'engineering'],
            turnSummary: raw.turnSummary || '',
          };
        }
      } catch { /* try next block */ }
      start = -1;
    }}
  }
  return null;
}

/** Parse batch response: { events: [...], pacing, reasoning } or single event fallback. */
function parseBatchResponse(text: string): DirectorEventBatch | null {
  let depth = 0, start = -1;
  for (let i = 0; i < text.length; i++) {
    if (text[i] === '{') { if (depth === 0) start = i; depth++; }
    if (text[i] === '}') { depth--; if (depth === 0 && start >= 0) {
      try {
        const raw = JSON.parse(text.slice(start, i + 1));

        if (Array.isArray(raw.events) && raw.events.length > 0) {
          const events: DirectorEvent[] = raw.events.map((e: any) => ({
            title: e.title || 'Untitled Event',
            description: e.description || e.crisis || '',
            options: (e.options || []).map((o: any, idx: number) => ({
              id: o.id || `option_${String.fromCharCode(97 + idx)}`,
              label: o.label || `Option ${String.fromCharCode(65 + idx)}`,
              description: o.description || '',
              isRisky: o.isRisky === true,
            })),
            riskyOptionId: e.riskyOptionId || e.options?.find((o: any) => o.isRisky)?.id || 'option_b',
            riskSuccessProbability: typeof e.riskSuccessProbability === 'number' ? e.riskSuccessProbability : 0.5,
            category: e.category || 'infrastructure',
            researchKeywords: e.researchKeywords || [],
            relevantDepartments: e.relevantDepartments || ['medical', 'engineering'],
            turnSummary: e.turnSummary || '',
          }));
          return { events, pacing: raw.pacing || 'normal', reasoning: raw.reasoning || '' };
        }

        if (raw.title && (raw.description || raw.crisis)) {
          const single = parseDirectorResponse(text.slice(start, i + 1));
          if (single) return { events: [single], pacing: 'normal', reasoning: 'single event' };
        }
      } catch { /* try next block */ }
      start = -1;
    }}
  }
  return null;
}

/** Fallback events if director fails. */
const FALLBACK_EVENTS: DirectorEvent[] = [
  {
    title: 'System Malfunction',
    description: 'A critical support component has developed an intermittent failure. Operating at 60% efficiency. Reserves are becoming dangerously low.',
    options: [
      { id: 'option_a', label: 'Emergency repair', description: 'Divert all engineering to immediate repair. Safe but halts all other construction for 2 weeks.', isRisky: false },
      { id: 'option_b', label: 'Improvised bypass', description: 'Build a bypass from non-standard parts. Faster but untested. Could fail catastrophically.', isRisky: true },
    ],
    riskyOptionId: 'option_b', riskSuccessProbability: 0.5, category: 'infrastructure',
    researchKeywords: ['life support failure', 'ECLSS redundancy'], relevantDepartments: ['engineering', 'medical'],
    turnSummary: 'Infrastructure strain triggered a life support component failure.',
  },
  {
    title: 'Supply Shortage',
    description: 'Unexpected contamination of reserves has rendered 30% of stored supplies unusable. The settlement must decide how to manage the shortfall.',
    options: [
      { id: 'option_a', label: 'Strict rationing', description: 'Reduce caloric intake by 25% colony-wide for 3 months. Morale will drop.', isRisky: false },
      { id: 'option_b', label: 'Emergency crop acceleration', description: 'Boost grow lights to 24/7, triple nutrient concentration. Could yield 2x harvest or kill the crops.', isRisky: true },
    ],
    riskyOptionId: 'option_b', riskSuccessProbability: 0.55, category: 'resource',
    researchKeywords: ['food security mars', 'hydroponic acceleration'], relevantDepartments: ['agriculture', 'medical'],
    turnSummary: 'Food contamination created an unexpected supply crisis.',
  },
  {
    title: 'Social Unrest',
    description: 'Tensions between work crews have escalated into a refusal to cooperate. Two factions have formed around competing visions. Productivity has dropped 40%.',
    options: [
      { id: 'option_a', label: 'Mediation program', description: 'Mandatory conflict resolution sessions. Slow but addresses root causes.', isRisky: false },
      { id: 'option_b', label: 'Restructure work crews', description: 'Break up existing teams and reassign. Disrupts established relationships.', isRisky: true },
    ],
    riskyOptionId: 'option_b', riskSuccessProbability: 0.45, category: 'psychological',
    researchKeywords: ['group conflict isolation', 'crew cohesion'], relevantDepartments: ['psychology', 'governance'],
    turnSummary: 'Accumulated social pressure erupted into factional conflict.',
  },
];

export class EventDirector {
  /**
   * Generate a turn event. Uses AgentOS generateText().
   */
  async generateEvent(ctx: DirectorContext, provider: LlmProvider = 'openai', model: string = 'gpt-5.4', instructions?: string): Promise<DirectorEvent> {
    const prompt = buildDirectorPrompt(ctx);
    const systemInstructions = instructions || DEFAULT_DIRECTOR_INSTRUCTIONS;

    try {
      const { generateText } = await import('@framers/agentos');
      const result = await generateText({
        provider,
        model,
        prompt: systemInstructions + '\n\n' + prompt,
      });

      const event = parseDirectorResponse(result.text);
      if (event) {
        console.log(`  [director] Generated: "${event.title}" (${event.category}) for ${ctx.leaderName}`);
        return event;
      }
      console.log(`  [director] Failed to parse response for ${ctx.leaderName}, using fallback`);
    } catch (err) {
      console.log(`  [director] Error for ${ctx.leaderName}: ${err}`);
    }

    // Fallback
    const fallback = FALLBACK_EVENTS[ctx.turn % FALLBACK_EVENTS.length];
    console.log(`  [director] Using fallback: "${fallback.title}"`);
    return { ...fallback };
  }

  /**
   * Generate 1 to maxEvents events for a turn.
   * Falls back to single-event generation if batch parsing fails.
   *
   * @param onUsage Optional callback invoked with the director's LLM
   *        response so the orchestrator can account for director spend in
   *        its cost telemetry. Director runs once per turn on the flagship
   *        model; without this hook the call was invisible to the per-run
   *        `cost` object returned by `runSimulation()`.
   */
  async generateEventBatch(
    ctx: DirectorContext,
    maxEvents: number = 3,
    provider: LlmProvider = 'openai',
    model: string = 'gpt-5.4',
    instructions?: string,
    onUsage?: (result: { usage?: { totalTokens?: number; promptTokens?: number; completionTokens?: number; costUSD?: number } }) => void,
    /**
     * Called with the raw caught error when the director's LLM call throws.
     * Lets the orchestrator classify the error (quota / auth / etc.) and
     * emit a `provider_error` SSE event before the existing fallback path
     * quietly substitutes canned events. Without this, a user whose API
     * credits run out would see the director keep producing the same three
     * fallback events across every turn with no explanation.
     */
    onProviderError?: (err: unknown) => void,
  ): Promise<DirectorEventBatch> {
    const prompt = buildDirectorPrompt(ctx, maxEvents);
    const systemInstructions = (instructions || DEFAULT_DIRECTOR_INSTRUCTIONS)
      .replace('{MAX_EVENTS}', String(maxEvents));

    try {
      const { generateText } = await import('@framers/agentos');
      // Prompt caching: the director instructions (~1500-2000 tokens) are
      // identical across all 6 turn calls in a run. Marking the system
      // block as a cache breakpoint lets Anthropic serve turns 2-6 from
      // its prefix cache at 0.1x cost. The per-turn context goes in the
      // user prompt and is NOT cached. Providers without cache support
      // (e.g. older OpenAI SDKs) ignore the breakpoint silently; for
      // OpenAI, prompt caching is automatic for prompts >=1024 tokens
      // and the block structure helps the hash align.
      const result = await generateText({
        provider,
        model,
        system: [{ text: systemInstructions, cacheBreakpoint: true }],
        prompt,
      });
      onUsage?.(result);

      const batch = parseBatchResponse(result.text);
      if (batch && batch.events.length > 0) {
        batch.events = batch.events.slice(0, maxEvents);
        console.log(`  [director] Generated ${batch.events.length} events (${batch.pacing}) for ${ctx.leaderName}: ${batch.events.map(e => `"${e.title}"`).join(', ')}`);
        return batch;
      }

      const single = parseDirectorResponse(result.text);
      if (single) {
        console.log(`  [director] Generated 1 event (single format) for ${ctx.leaderName}: "${single.title}"`);
        return { events: [single], pacing: 'normal', reasoning: 'parsed as single event' };
      }

      console.log(`  [director] Failed to parse batch for ${ctx.leaderName}, using fallback`);
    } catch (err) {
      console.log(`  [director] Batch error for ${ctx.leaderName}: ${err}`);
      // Surface the raw error so the orchestrator can classify it. We
      // still fall through to the canned fallback so a single transient
      // error does not break the turn, but a terminal quota/auth error
      // will flip the run-scoped abort flag and subsequent turns will
      // short-circuit.
      onProviderError?.(err);
    }

    const fallback = FALLBACK_EVENTS[ctx.turn % FALLBACK_EVENTS.length];
    console.log(`  [director] Using fallback: "${fallback.title}"`);
    return { events: [{ ...fallback }], pacing: 'normal', reasoning: 'fallback' };
  }

  /** @deprecated Use generateEvent */
  async generateCrisis(ctx: DirectorContext, provider: LlmProvider = 'openai', model: string = 'gpt-5.4', instructions?: string): Promise<DirectorEvent> {
    return this.generateEvent(ctx, provider, model, instructions);
  }

  /**
   * Get a milestone crisis (Turn 1 or final turn).
   * These are fixed for narrative anchoring.
   */
  getMilestoneCrisis(turn: number, maxTurns: number): DirectorCrisis | null {
    if (turn === 1) {
      const s = SCENARIOS[0];
      return {
        title: s.title,
        description: s.crisis,
        crisis: s.crisis,
        options: s.options || [
          { id: 'option_a', label: 'Arcadia Planitia', description: 'Flat basalt plains, safe, ice access', isRisky: false },
          { id: 'option_b', label: 'Valles Marineris rim', description: 'Canyon rim, mineral rich, hazardous terrain', isRisky: true },
        ],
        riskyOptionId: 'option_b',
        riskSuccessProbability: s.riskSuccessProbability,
        category: 'infrastructure',
        researchKeywords: s.researchKeywords,
        relevantDepartments: ['medical', 'engineering'],
        turnSummary: 'Colony ship in orbit. Safe plains or mineral-rich canyon rim: the first decision shapes everything.',
      };
    }

    if (turn === maxTurns) {
      const s = SCENARIOS[11]; // Legacy Assessment
      const crisisText = s?.crisis || 'Earth requests a comprehensive status report on your colony. Assess your legacy.';
      return {
        title: s?.title || 'Legacy Assessment',
        description: crisisText,
        crisis: crisisText,
        options: [
          { id: 'option_a', label: 'Honest assessment', description: 'Report factually, including failures and regrets', isRisky: false },
          { id: 'option_b', label: 'Ambitious projection', description: 'Emphasize achievements, propose bold next-century vision', isRisky: true },
        ],
        riskyOptionId: 'option_b',
        riskSuccessProbability: 0.5,
        category: 'political',
        researchKeywords: ['Mars colony long-term projections'],
        relevantDepartments: ['governance', 'psychology', 'medical', 'engineering'],
        turnSummary: 'Earth demands a full status report. The commander must decide: honest accounting of failures, or bold vision for the next century.',
      };
    }

    return null; // Not a milestone turn
  }
}

/** @deprecated Use EventDirector */
export const CrisisDirector = EventDirector;
