/**
 * Zod schemas for the Event Director's batch output.
 *
 * Replaces the hand-rolled regex parser in the old director.ts. The
 * `.refine()` on DirectorEventSchema enforces the risky-option invariant
 * that the old parser silently accepted when the LLM pointed riskyOptionId
 * at a non-risky option.
 *
 * @module paracosm/runtime/schemas/director
 */
import { z } from 'zod';

/** A single choice presented to the commander. */
export const DirectorOptionSchema = z.object({
  id: z.string().regex(/^option_[a-c]$/, 'id must be option_a/b/c'),
  label: z.string().min(1),
  description: z.string().min(1),
  isRisky: z.boolean(),
});

/** One event generated by the director for a turn. */
export const DirectorEventSchema = z.object({
  title: z.string().min(1),
  description: z.string().min(1),
  options: z.array(DirectorOptionSchema).min(2).max(3),
  riskyOptionId: z.string(),
  riskSuccessProbability: z.number().min(0).max(1),
  category: z.string().min(1),
  researchKeywords: z.array(z.string()).default([]),
  relevantDepartments: z.array(z.string()).min(1),
  turnSummary: z.string().min(1),
}).refine(
  evt => evt.options.some(o => o.id === evt.riskyOptionId && o.isRisky),
  { message: 'riskyOptionId must reference an option where isRisky=true' },
);

/** Full batch response — 1 to 3 events plus pacing + reasoning. */
export const DirectorEventBatchSchema = z.object({
  events: z.array(DirectorEventSchema).min(1).max(3),
  pacing: z.enum(['calm', 'normal', 'intense']),
  reasoning: z.string().default(''),
});

export type DirectorOptionZ = z.infer<typeof DirectorOptionSchema>;
export type DirectorEventZ = z.infer<typeof DirectorEventSchema>;
export type DirectorEventBatchZ = z.infer<typeof DirectorEventBatchSchema>;
